- name: Installing additional packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - nginx
    - zsh
    - git
    - language-pack-en

- name: Clone oh-my-zsh repo
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/vagrant/.oh-my-zsh

- name: Create a new zsh config from the template in the repo
  command: cp /home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc

- name: Set zsh as default shell
  become: yes
  user: 
    name: vagrant
    shell: /usr/bin/zsh

- name: Set agnoster as zsh theme
  lineinfile:
    path: /home/vagrant/.zshrc
    regexp: ^(.*)ZSH_THEME="robbyrussell"$
    line: ZSH_THEME="agnoster"


# - name: Backing up existing ~/.zshrc
#   shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.pre-oh-my-zsh; fi
#   when: installation is success

# - name: Cloning oh-my-zsh
#   git:
#     repo=https://github.com/robbyrussell/oh-my-zsh
#     dest=~/.oh-my-zsh
#   when: installation is success
#   register: cloning

# - name: Creating new ~/.zshrc
#   copy:
#     src=~/.oh-my-zsh/templates/zshrc.zsh-template
#     dest=~/.zshrc
#   when: cloning is success